<a href="https://colab.research.google.com/github/rk76977/MAT-422/blob/main/1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.2.1. Linear spaces**

# **Confusion**

### Gaussian elimintation as an algorithm to return a basis of the row space of a matrix

Import numpy

In [1]:
import numpy as np

Helper function to return matrix of given size

In [2]:
def matrix(m,n):
  return np.random.rand(m,n)

In [3]:
matrix=matrix(4,4)

Algorithm to return basis for row space from gaussian elimination

In [4]:
def basis_from_GE(matrix):
  rowsize,colsize=matrix.shape
  row=0
  col=0
  while(row<rowsize and col<colsize):

    nonzeroindex=-1
    for i in range(row,rowsize):
      if(matrix[i][col] != 0):
        nonzeroindex=i
        i=rowsize
        break
    matrix[[row,nonzeroindex]]=matrix[[nonzeroindex,row]]
    if(nonzeroindex>=0):
      for i in range(row+1,rowsize):
        matrix[i]=matrix[i]-(matrix[i][col]/matrix[nonzeroindex][col])*matrix[nonzeroindex]
    col+=1
    if(nonzeroindex>=0):
      row+=1
  for i in range(rowsize):
    allzeros=True
    for j in range(colsize):
      if matrix[i][j] != 0:
        allzeros=False
    if(allzeros):
      np.delete(matrix,i,axis=1)
  return matrix

In [5]:
print("matrix row space:")
print(matrix)
print("basis for row space")
print(basis_from_GE(matrix))

matrix row space:
[[0.95119954 0.01903379 0.80992993 0.28677576]
 [0.71135202 0.08524528 0.04278641 0.02960308]
 [0.20448431 0.09148092 0.1432456  0.33480938]
 [0.90917115 0.58170309 0.43785817 0.81779435]]
basis for row space
[[ 0.95119954  0.01903379  0.80992993  0.28677576]
 [ 0.          0.07101091 -0.56291751 -0.1848614 ]
 [ 0.          0.          0.6618816   0.5006582 ]
 [ 0.          0.          0.         -1.1139188 ]]


The idea is that each row is a linear combination of the initial rows, and if $c_1 r_1 \dots c_m r_m =0$, where the $r_i$'s are the members of the basis, then in the $k$th nonzero column, row $r_k$ will contain nonnegative value, so by induction $c_k =0$, so the $r_i$'s are a basis.

## **1.2.2. Orthogonality**

### Verifying Cauchy in $R^n$

Generating $u$ and $v$ in some $R^n$ and computing $|u \cdot v|$ and $|u| \cdot |v|$

In [6]:
n=100

def dot(u,v):
  return np.dot(u,v.T)
def norm(u):
  return np.linalg.norm(u)

for i in range(3):
  u=np.random.rand(1,n)
  v=np.random.rand(1,n)

  x1=norm(u)*norm(v)
  x2=norm(dot(u,v))
  if(x1>=x2):
    print("|u||v| = {} >= {} = |u (dot) v|".format(x1,x2))


|u||v| = 31.698446658817737 >= 23.204570230755866 = |u (dot) v|
|u||v| = 33.162911637164974 >= 23.70148293697227 = |u (dot) v|
|u||v| = 35.68335917177873 >= 27.132777782075994 = |u (dot) v|
