<a href="https://colab.research.google.com/github/rk76977/MAT-422/blob/main/1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.2.1. Linear spaces**

### Gaussian elimintation as an algorithm to return a basis of the row space of a matrix

Import numpy

In [94]:
import numpy as np

Helper function to return matrix of given size

In [95]:
def matrix(m,n):
  return np.random.rand(m,n)

In [96]:
matrix=matrix(4,4)

Algorithm to return basis for row space from gaussian elimination

In [97]:
def basis_from_GE(matrix):
  rowsize,colsize=matrix.shape
  row=0
  col=0
  while(row<rowsize and col<colsize):

    nonzeroindex=-1
    for i in range(row,rowsize):
      if(matrix[i][col] != 0):
        nonzeroindex=i
        i=rowsize
        break
    matrix[[row,nonzeroindex]]=matrix[[nonzeroindex,row]]
    if(nonzeroindex>=0):
      for i in range(row+1,rowsize):
        matrix[i]=matrix[i]-(matrix[i][col]/matrix[nonzeroindex][col])*matrix[nonzeroindex]
    col+=1
    if(nonzeroindex>=0):
      row+=1
  for i in range(rowsize):
    allzeros=True
    for j in range(colsize):
      if matrix[i][j] != 0:
        allzeros=False
    if(allzeros):
      np.delete(matrix,i,axis=1)
  return matrix








In [98]:
print("matrix row space:")
print(matrix)
print("basis for row space")
print(basis_from_GE(matrix))

matrix row space:
[[0.08519527 0.63189868 0.86643565 0.25204831]
 [0.63678451 0.77331784 0.33160065 0.111182  ]
 [0.74214633 0.8718583  0.13700714 0.57238137]
 [0.40717324 0.77368893 0.98498481 0.54479484]]
basis for row space
[[ 0.08519527  0.63189868  0.86643565  0.25204831]
 [ 0.         -3.9497528  -6.14449575 -1.77273074]
 [ 0.          0.         -0.20370455  0.45600403]
 [ 0.          0.          0.          1.10633785]]


The idea is that each row is a linear combination of the initial rows, and if $c_1 r_1 \dots c_m r_m =0$, where the $r_i$'s are the members of the basis, then in the $k$th nonzero column, row $r_k$ will contain nonnegative value, and by induction $c_k =0$, so the $r_i$'s are a basis.

## **1.2.2. Orthogonality**

### Verifying Cauchy in $R^n$

Generating $u$ and $v$ in some $R^n$ and computing $|u \cdot v|$ and $|u| \cdot |v|$

In [99]:
n=100

def dot(u,v):
  return np.dot(u,v.T)
def norm(u):
  return np.linalg.norm(u)

for i in range(3):
  u=np.random.rand(1,n)
  v=np.random.rand(1,n)

  x1=norm(u)*norm(v)
  x2=norm(dot(u,v))
  if(x1>=x2):
    print("|u||v| = {} >= {} = |u (dot) v|".format(x1,x2))


|u||v| = 34.3190235340631 >= 27.09939276638048 = |u (dot) v|
|u||v| = 31.313972203060267 >= 23.585132979754942 = |u (dot) v|
|u||v| = 30.910654131178653 >= 22.010285729984773 = |u (dot) v|
