<a href="https://colab.research.google.com/github/rk76977/MAT-422/blob/main/1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.2.1. Linear spaces**

### Gaussian elimintation as an algorithm to return a basis of the row space of a matrix

Import numpy

In [1]:
import numpy as np

Helper function to return matrix of given size

In [2]:
def matrix(m,n):
  return np.random.rand(m,n)

In [6]:
matrix=matrix(4,4)

Algorithm to return basis for row space from gaussian elimination

In [5]:
def basis_from_GE(matrix):
  rowsize,colsize=matrix.shape
  row=0
  col=0
  while(row<rowsize and col<colsize):

    nonzeroindex=-1
    for i in range(row,rowsize):
      if(matrix[i][col] != 0):
        nonzeroindex=i
        i=rowsize
        break
    matrix[[row,nonzeroindex]]=matrix[[nonzeroindex,row]]
    if(nonzeroindex>=0):
      for i in range(row+1,rowsize):
        matrix[i]=matrix[i]-(matrix[i][col]/matrix[nonzeroindex][col])*matrix[nonzeroindex]
    col+=1
    if(nonzeroindex>=0):
      row+=1
  for i in range(rowsize):
    allzeros=True
    for j in range(colsize):
      if matrix[i][j] != 0:
        allzeros=False
    if(allzeros):
      np.delete(matrix,i,axis=1)
  return matrix

In [7]:
print("matrix row space:")
print(matrix)
print("basis for row space")
print(basis_from_GE(matrix))

matrix row space:
[[0.45727766 0.89541867 0.05770734 0.66831929]
 [0.04074901 0.86130132 0.79472555 0.19585897]
 [0.46441201 0.49512829 0.95307956 0.53743122]
 [0.03757624 0.66274057 0.7510168  0.68233123]]
basis for row space
[[ 0.45727766  0.89541867  0.05770734  0.66831929]
 [ 0.          0.78150862  0.78958312  0.13630358]
 [ 0.          0.          1.31301251 -0.06906352]
 [ 0.          0.          0.          0.5326008 ]]


The idea is that each row is a linear combination of the initial rows, and if $c_1 r_1 \dots c_m r_m =0$, where the $r_i$'s are the members of the basis, then in the $k$th nonzero column, row $r_k$ will contain nonnegative value, so by induction $c_k =0$, so the $r_i$'s are a basis.

## **1.2.2. Orthogonality**

### Verifying Cauchy in $R^n$

Generating $u$ and $v$ in some $R^n$ and computing $|u \cdot v|$ and $|u| \cdot |v|$

In [8]:
n=100

def dot(u,v):
  return np.dot(u,v.T)
def norm(u):
  return np.linalg.norm(u)

for i in range(3):
  u=np.random.rand(1,n)
  v=np.random.rand(1,n)

  x1=norm(u)*norm(v)
  x2=norm(dot(u,v))
  if(x1>=x2):
    print("|u||v| = {} >= {} = |u (dot) v|".format(x1,x2))


|u||v| = 30.05869748048513 >= 22.471132574776753 = |u (dot) v|
|u||v| = 30.9495741035045 >= 22.579160213078882 = |u (dot) v|
|u||v| = 32.62641362764654 >= 23.829166433266952 = |u (dot) v|
