<a href="https://colab.research.google.com/github/rk76977/MAT-422/blob/main/1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.4.1. Singular value decomposition**

### Illustration of nonuniqueness of $\mathbf{u},\mathbf{v}$.

I think I originally was going to try to write an algorithm for singular value decomposition, but I think implementing it would be too long. I think it would involve finding all positive eigenvalues of $\mathbf{A}^T \mathbf{A}$, then finding a basis for each corresponding null space for each eigenspace, then using gram schmidt to convert each basis into an orthonormal basis, then dividing all eigenvectors by their eigenvalue to find $\mathbf{u}$, and then extending the basis of $\mathbf{u}$ to $\mathbb{R}^m$ to complete $\mathbf{u}$ (by listing the current $\mathbf{u}$'s and a basis of $\mathbb{R}^m$ and linearly removing vals that are in the previous span set by reducing a matrix that is taller than wide and checking if the equations after the smaller dimension are inconsistent).

Another concept, though, is that for the $n-r$ $\mathbf{v}$'s that are in the eigenspace with $e=0$, (i.e, the null space), because $\mathbf{A}\mathbf{v} = 0$, the corresponding $\mathbf{u}$'s are also $0$, so the list of nonzero $\mathbf{u}$'s is extended to a basis of $\mathbb{R}^m$ so that $\mathbf{U}$ is orthogonal.



I made a simple example of swapping the $\mathbf{u}$'s

Import numpy

In [2]:
import numpy as np

In [19]:
S=np.array([[2,0,0],[0,1,0],[0,0,0]])
V_inv=np.linalg.inv(np.array([[-1,0,0],[0,0,-1],[0,1,0]]))
for i in range(3):
  U = np.array([[1,0,i],[0,1,i+1],[0,0,i+2]])
  print("U S V^-1 = \n\n{}".format(U@ S@ V_inv))


U S V^-1 = 

[[-2.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
U S V^-1 = 

[[-2.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
U S V^-1 = 

[[-2.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


Note that, since the last column of U is not in any linear combination from S, it doesn't change the result.

Sorry, for **1.4.2. Low-rank matrix approximations** and **1.4.3. Principal component analysis**, these sections look interesting but I ran out of time to include concepts on here. Sorry.