<a href="https://colab.research.google.com/github/rk76977/MAT-422/blob/main/1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.4.1. Singular value decomposition**

### Algorithm for QR decomposition for vectors in $\mathbb{R}^n$

Import numpy

In [ ]:
import numpy as np

Helper function to get matrix with linearly independent columns of given size. This is done by finding an invertible square matrix that the given dimensions fit in and returning the invertible matrix over the given dimensions. This ensures the column vectors of the returned matrix are linearly independent.

In [ ]:
def Matrix(m,n):
  squaresize=max(m,n)
  invertible=False
  while(not invertible):
    M=np.random.rand(squaresize,squaresize)
    if(np.linalg.det(M)!=0.0):
      return M[:m,:n]

In [ ]:
matrix=Matrix(8,4)
print("M: \n {}".format(matrix))

M: 
 [[0.41 0.94 0.72 0.73]
 [0.44 0.24 0.98 0.09]
 [0.75 0.93 0.58 0.93]
 [0.75 0.03 0.96 0.44]
 [0.18 0.43 0.87 0.88]
 [0.84 0.5  0.05 0.09]
 [0.95 0.51 0.03 0.61]
 [0.49 0.29 0.28 0.36]]


Helper functions for dot product and norms of column vectors

In [ ]:
def Dot(u,v):
  return np.dot(u,v.T)
def Norm(u):
  return np.linalg.norm(u)

Algorithm to return the QR decomposition of a given matrix, returns Q and R. This is done by applying Gram-Schmidt and keeping track of each dot product between values in the orthogonal set U and each vector V. The $i$th column of $\mathbf{R}$ consists of the $i$ values $(u_1 \cdot v_i), \dots , (u_{i-1} \cdot v_i), |u_i|$.

In [ ]:
def QA_decomposition(matrix):
  m,n = matrix.shape
  V=[matrix[:,j] for j in range(n)]
  U=[]
  Q=np.zeros((m,n))
  R=np.zeros((n,n))

  for i in range(n):
    v=V[i]
    ###Compute the dot product of v and each u currently in U (the orthogonal basis)
    ###And store these coefficients in a list
    ###These i-1 coefficients  will be written in the ith column in Q
    ###(The ith coefficient will be the norm of of u_i)
    coefficients=[]
    ###Compute dot products
    ###(If i=0, no dot products are taken since U is empty)
    for k in range(i):
      coefficients.append(Dot(U[k],v))
    ###Compute othogonal projection of new v onto U
    ###(If i = 0, no subtraction occurs)
    if(i==0):
      u_before_norm = v
    else:
      u_dot_v_list=[U[i]*coefficients[i] for i in range(len(U))]
      u_dot_v_matrix=np.column_stack(u_dot_v_list)

      u_before_norm = v - np.sum(u_dot_v_matrix,axis=1)
    norm=Norm(u_before_norm)


    coefficients.append(norm)
    ###Coefficients now consistents of i total values

    #Compute and append u to U
    u=u_before_norm/norm
    U.append(u)

    #Append coefficients, top down, to ith column
    for j in range(0,i+1):
      R[j][i]=coefficients[j]

  #Collect u's as columns into Q
  Q=np.column_stack(U)
  return Q, R

In [ ]:
Q,R = QA_decomposition(matrix)
np.set_printoptions(precision=2, suppress=True, linewidth=80)
print("M: \n {}".format(matrix))
print("Q: \n {}".format(Q))
print("R: \n {}".format(R))

M: 
 [[0.41 0.94 0.72 0.73]
 [0.44 0.24 0.98 0.09]
 [0.75 0.93 0.58 0.93]
 [0.75 0.03 0.96 0.44]
 [0.18 0.43 0.87 0.88]
 [0.84 0.5  0.05 0.09]
 [0.95 0.51 0.03 0.61]
 [0.49 0.29 0.28 0.36]]
Q: 
 [[ 0.22  0.67  0.12 -0.22]
 [ 0.24 -0.07  0.52 -0.57]
 [ 0.41  0.41 -0.07  0.16]
 [ 0.41 -0.5   0.49  0.18]
 [ 0.1   0.31  0.45  0.5 ]
 [ 0.46 -0.08 -0.35 -0.44]
 [ 0.52 -0.15 -0.39  0.34]
 [ 0.27 -0.05 -0.01  0.1 ]]
R: 
 [[1.84 1.27 1.22 1.28]
 [0.   0.98 0.43 0.8 ]
 [0.   0.   1.38 0.4 ]
 [0.   0.   0.   0.66]]


Comparing $\mathbf{M}$ and $\mathbf{Q} \cdot \mathbf{R}$

In [ ]:
np.set_printoptions(precision=2, suppress=True, linewidth=80)
print("M: \n {}".format(matrix))
QR= Q @ R
print("QR: \n {}".format(QR))

M: 
 [[0.41 0.94 0.72 0.73]
 [0.44 0.24 0.98 0.09]
 [0.75 0.93 0.58 0.93]
 [0.75 0.03 0.96 0.44]
 [0.18 0.43 0.87 0.88]
 [0.84 0.5  0.05 0.09]
 [0.95 0.51 0.03 0.61]
 [0.49 0.29 0.28 0.36]]
QR: 
 [[0.41 0.94 0.72 0.73]
 [0.44 0.24 0.98 0.09]
 [0.75 0.93 0.58 0.93]
 [0.75 0.03 0.96 0.44]
 [0.18 0.43 0.87 0.88]
 [0.84 0.5  0.05 0.09]
 [0.95 0.51 0.03 0.61]
 [0.49 0.29 0.28 0.36]]


Comparing $\mathbf{Q}^T  \mathbf{Q}$ and $\mathbf{I}$

In [ ]:
np.set_printoptions(precision=2, suppress=True, linewidth=80)
I=np.eye(matrix.shape[1])
print("I: \n {}".format(I))
QR= Q @ R
print("Q^tQ: \n {}".format(Q.T @ Q))

I: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Q^tQ: 
 [[ 1. -0.  0. -0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1. -0.]
 [-0.  0. -0.  1.]]


**(Pog)**

## **1.3.2. Least-squares problems**

### Solving least squares with normal equations

Computing $\mathbf{x} = (\mathbf{A}^T \mathbf{A})^{-1}\mathbf{A}^T\mathbf{y}$ and checking $|\mathbf{A}\mathbf{x}-\mathbf{y}|$ (despite less numerical stability than QR decomposition)

In [ ]:
for i in range(10):
  a=Matrix(30,5)
  y=Matrix(30,1)
  x=(np.linalg.inv(a.T @ a)) @ ((a.T @ y))
  print("|Ax-y|={}".format((Norm(a@x-y))))

|Ax-y|=1.333701010640906
|Ax-y|=1.5109601621234359
|Ax-y|=1.8323020899624063
|Ax-y|=1.6630361856370015
|Ax-y|=1.4908089670513018
|Ax-y|=1.5235429503112203
|Ax-y|=1.7337712265180067
|Ax-y|=1.7029998637280133
|Ax-y|=1.6947771205638207
|Ax-y|=1.602404661766153


(I think the >1 values might likely due to such numerical instability. I did not compare it to QR, though, sorry).

## **1.3.3. Linear regression**

### Sorry, I didn't include anything extra for this section.